CustomerWebApplication/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Customer.Web.Services.Basket;
using Customer.Web.Services.Product;
using Customer.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Customer.Web.Controllers
{
    public class BasketController : Controller
    {
        private readonly ILogger _logger;
        private readonly IBasketFacade _basketFacade;
        private readonly IProductFacade _productFacade;

        public BasketController(ILogger<BasketController> logger,
                                IBasketFacade basketFacade,
                                IProductFacade productFacade)
        {
            _logger = logger;
            _basketFacade = basketFacade;
            _productFacade = productFacade;
        }

        // GET : Basket
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<BasketItemDto> basketItems = null;
            try
            {
                basketItems = await _basketFacade.GetBasket(1);
                /*basketItems = await _basketFacade.GetBasket(customerId);*/
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Basket Facade");
                basketItems = null;
            }

            IEnumerable<BasketItemViewModel> viewModel = basketItems.Select(b => new BasketItemViewModel
            {
                ProductId = b.ProductId,
                Name = b.ProductName,
                Quantity = b.Quantity,
                Price = b.Price
            });

            return View(viewModel);
        }

        // GET : Basket/AddItem/5
        [HttpGet]
        public async Task<IActionResult> AddItem([FromQuery] int ProductId)
        {
            ProductDto product = null;
            try
            {
                product = await _productFacade.GetProduct(ProductId);
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Basket Facade");
                product = null;
            }

            BasketItemViewModel viewModel = new BasketItemViewModel
            {
                ProductId = product.ProductId,
                Name = product.Name,
                Description = product.Description,
                BrandId = product.BrandId,
                Brand = product.Brand,
                CategoryId = product.CategoryId,
                Category = product.Category,
                Price = product.Price
            };

            return View(viewModel);
        }

        // Post : Basket/AddItem/5
        [HttpPost]
        public async Task<IActionResult> AddItem([Bind("ProductId,Quantity")] BasketItemDto newItem)
        {
            try
            {
                await _basketFacade.AddItem(newItem);
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Basket Facade");
            }

            return RedirectToAction("Items", "Products");
        }

        // Get : Basket/RemoveItem/
        [HttpGet]
        public async Task<IActionResult> RemoveItem([FromQuery] int ProductId)
        {
            try
            {
                await _basketFacade.RemoveItem(1, ProductId);
                /*await _basketFacade.RemoveItem(customerId, ProductId);*/
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Basket Facade");
            }

            return RedirectToAction("Items");
        }
    }
}

CustomerWebApplication/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Customer.Web.Services.Basket;
using Customer.Web.Services.Order;
using Customer.Web.Services.Review;
using Customer.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CustomerWebApplication.Controllers
{
    public class OrderController : Controller
    {
        private readonly ILogger _logger;
        private readonly IOrderFacade _orderFacade;
        private readonly IBasketFacade _basketFacade;
        private readonly IReviewFacade _reviewFacade;

        public OrderController(ILogger<OrderController> logger,
                                IOrderFacade orderFacade,
                                IBasketFacade basketFacade,
                                IReviewFacade reviewFacade)
        {
            _logger = logger;
            _orderFacade = orderFacade;
            _basketFacade = basketFacade;
            _reviewFacade = reviewFacade;
        }

        // GET: Order
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<BasketItemDto> basketItems = null;
            try
            {
                basketItems = await _basketFacade.GetBasket(1);
                /*basketItems = await _basketFacade.GetBasket(customerId);*/
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Basket Facade");
                basketItems = null;
            }

            IEnumerable<OrderedItemViewModel> orderedItems = basketItems.Select(b => new OrderedItemViewModel
            {
                ProductId = b.ProductId,
                Quantity = b.Quantity,
                Price = b.Price,
                ProductName = b.ProductName,
            });

            double totalPrice = 0;
            foreach (OrderedItemViewModel item in orderedItems)
            {
                totalPrice = totalPrice + (item.Price * item.Quantity);
            };

            OrderViewModel viewModel = new OrderViewModel()
            {
                CustomerId = 1,
                /*CustomerId = customerId,*/
                OrderedItems = orderedItems,
                TotalPrice = totalPrice,
            };

            return View(viewModel);
        }

        // POST: Create
        [HttpPost]
        public async Task<IActionResult> Create()
        {
            IEnumerable<BasketItemDto> basketItems = null;
            try
            {
                basketItems = await _basketFacade.GetBasket(1);
                /*basketItems = await _basketFacade.GetBasket(customerId);*/
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Basket Facade");
                basketItems = null;
            }

            double totalPrice = 0;
            foreach (BasketItemDto item in basketItems)
            {
                totalPrice = totalPrice + (item.Price * item.Quantity);
            };

            try
            {
                OrderDto newOrder = new OrderDto
                {
                    CustomerId = 1,
                   /* CustomerId = customerId,*/
                   Date = DateTime.Now,
                   OrderedItems = basketItems.Select(i => new OrderedItemDto
                   {
                       ProductId = i.ProductId,
                       ProductName = i.ProductName,
                       Quantity = i.Quantity,
                       Price = i.Price,
                   }).ToList(),
                   TotalPrice = totalPrice
                };

                await _orderFacade.NewOrder(newOrder);
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Order Facade");
            }

            return RedirectToAction("index", "basket");
        }

        // GET: Order/History
        public async Task<IActionResult> History()
        {
            IEnumerable<OrderHistoryDto> orderHistory = null;
            try
            {
                orderHistory = await _orderFacade.GetOrders(1);
                /*orderHistory = await _orderFacade.GetOrders(customerId);*/
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Order Facade");
                orderHistory = null;
            }

            IEnumerable<OrderHistoryViewModel> viewModel = orderHistory.Select(o => new OrderHistoryViewModel
            {
                OrderId = o.OrderId,
                Date = o.Date,
                TotalPrice = o.TotalPrice,
            });

            return View(viewModel);
        }

        public async Task<IActionResult> Details(int orderId)
        {
            OrderDto order = null;
            try
            {
                order = await _orderFacade.GetOrder(orderId);
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Order Facade");
                order = null;
            }

            IEnumerable<ReviewDto> reviews = null;
            try
            {
                reviews = await _reviewFacade.GetCustomerReviews(1);
                /*reviews = await _reviewFacade.GetCustomerReviews(customerId);*/
            }
            catch (HttpRequestException)
            {
                _logger.LogWarning("Exception Occured using Review Facade");
                reviews = null;
            }

            List<OrderedItemViewModel> orderedItems = order.OrderedItems.Select(b => new OrderedItemViewModel
            {
                ProductId = b.ProductId,
                Quantity = b.Quantity,
                Price = b.Price,
                ProductName = b.ProductName,
            }).ToList();

            foreach (var item in orderedItems)
            {
                if(reviews.Any(r => r.ProductId == item.ProductId))
                {
                    item.hasReviewed = true;
                }
            }

            OrderViewModel viewModel = new OrderViewModel
            {
                OrderId = order.OrderId,
                Date = order.Date,
                OrderedItems = orderedItems,
                TotalPrice = order.TotalPrice,
            };

            return View(viewModel);
        }
    }
}

CustomerWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ThreeAmigos Corp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ThreeAmigos Corp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">Basket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="History">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Review" asp-action="History">Reviews</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Details">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout" asp-route-returnUrl="">Logout</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CustomerWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>